apiVersion: esk.io/v1alpha1
kind: SecretBinding
metadata:
  name: esk-complex-bind
  namespace: default
spec:
  serviceAccount: default
  secrets:
    - name: esk-vault-example
    - name: esk-gcp-example
  template: |
    vault={{ esk-vault-example.pass }}
    gcp={{ test-gcp.pass }}
    gcp_test={{ test-gcp.gcp }}
  target: /tmp/test.txt