FROM esk8s/esk-base:1.0.0

RUN pip install --pre kopf moment

COPY esk/engine /app/engine
COPY esk/operator /app/operator

WORKDIR /app/operator
ENTRYPOINT [ "kopf", "run", "--log-format=full", "-v", "main.py" ]